[project]
name = "revolt_cli"
version = "0.1.0"
description = "usefullness tools in one cli"
authors = ["Evgeniy Khristenko hristenko.evgeniy@yandex.ru"]
readme = "README.md"
packages = [{ include = "revolt_cli" }]
requires-python = ">=3.9"

[tool.poetry.dependencies]
python = "^3.9"
scapy = "^2.5.0"
netifaces = "^0.11.0"
python-dotenv = "^1.1.1"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.0.0"
pytest = "^7.0.0"
black = "^23.0.0"

[project.scripts]
myarp = "app_py.cli:main"